//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 07:42:28 AM BST 
//


package fs2013;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}farmSiloAmounts"/>
 *         &lt;element ref="{}fillTypePrices"/>
 *         &lt;element ref="{}rains"/>
 *         &lt;element ref="{}currentRain"/>
 *         &lt;element ref="{}lastRain"/>
 *       &lt;/sequence>
 *       &lt;attribute name="autoBackupIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="completedMowingMissions" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="completedTransportMissions" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="currentDay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="dayTime" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="densityMapRevision" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="difficulty" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="eastState1" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="eastState2" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="expenses" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="foundHelpIcons" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="foundHorseshoeCount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="foundHorseshoes" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fuelUsage" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="hectaresSeeded" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="hectaresThreshed" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="hectaresWorked" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="loan" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="loanAnnualInterestRate" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="longSnowBreakCounter" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="mapId" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="missionFrequency" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="money" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="plantGrowthRate" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="playTime" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="resetVehicles" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="revenue" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="revision" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="saveDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="seedUsage" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="seedingDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="showIconsOnPDA" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="threshingDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="timeScale" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="timeSinceLastRain" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="traveledDistance" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="valid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "farmSiloAmounts",
    "fillTypePrices",
    "rains",
    "currentRain",
    "lastRain"
})
@XmlRootElement(name = "careerSavegame")
public class CareerSavegame {

    @XmlElement(required = true)
    protected FarmSiloAmounts farmSiloAmounts;
    @XmlElement(required = true)
    protected FillTypePrices fillTypePrices;
    @XmlElement(required = true)
    protected Rains rains;
    @XmlElement(required = true)
    protected CurrentRain currentRain;
    @XmlElement(required = true)
    protected LastRain lastRain;
    @XmlAttribute(name = "autoBackupIndex", required = true)
    protected BigInteger autoBackupIndex;
    @XmlAttribute(name = "completedMowingMissions", required = true)
    protected BigInteger completedMowingMissions;
    @XmlAttribute(name = "completedTransportMissions", required = true)
    protected BigInteger completedTransportMissions;
    @XmlAttribute(name = "currentDay", required = true)
    protected BigInteger currentDay;
    @XmlAttribute(name = "dayTime", required = true)
    protected BigDecimal dayTime;
    @XmlAttribute(name = "densityMapRevision", required = true)
    protected BigInteger densityMapRevision;
    @XmlAttribute(name = "difficulty", required = true)
    protected BigInteger difficulty;
    @XmlAttribute(name = "eastState1", required = true)
    protected BigInteger eastState1;
    @XmlAttribute(name = "eastState2", required = true)
    protected BigInteger eastState2;
    @XmlAttribute(name = "expenses", required = true)
    protected BigDecimal expenses;
    @XmlAttribute(name = "foundHelpIcons", required = true)
    protected BigInteger foundHelpIcons;
    @XmlAttribute(name = "foundHorseshoeCount", required = true)
    protected BigInteger foundHorseshoeCount;
    @XmlAttribute(name = "foundHorseshoes", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String foundHorseshoes;
    @XmlAttribute(name = "fuelUsage", required = true)
    protected BigDecimal fuelUsage;
    @XmlAttribute(name = "hectaresSeeded", required = true)
    protected BigDecimal hectaresSeeded;
    @XmlAttribute(name = "hectaresThreshed", required = true)
    protected BigDecimal hectaresThreshed;
    @XmlAttribute(name = "hectaresWorked", required = true)
    protected BigDecimal hectaresWorked;
    @XmlAttribute(name = "loan", required = true)
    protected BigInteger loan;
    @XmlAttribute(name = "loanAnnualInterestRate", required = true)
    protected BigInteger loanAnnualInterestRate;
    @XmlAttribute(name = "longSnowBreakCounter", required = true)
    protected BigInteger longSnowBreakCounter;
    @XmlAttribute(name = "mapId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String mapId;
    @XmlAttribute(name = "missionFrequency", required = true)
    protected BigInteger missionFrequency;
    @XmlAttribute(name = "money", required = true)
    protected BigInteger money;
    @XmlAttribute(name = "plantGrowthRate", required = true)
    protected BigInteger plantGrowthRate;
    @XmlAttribute(name = "playTime", required = true)
    protected BigDecimal playTime;
    @XmlAttribute(name = "resetVehicles", required = true)
    protected boolean resetVehicles;
    @XmlAttribute(name = "revenue", required = true)
    protected BigDecimal revenue;
    @XmlAttribute(name = "revision", required = true)
    protected BigInteger revision;
    @XmlAttribute(name = "saveDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar saveDate;
    @XmlAttribute(name = "seedUsage", required = true)
    protected BigDecimal seedUsage;
    @XmlAttribute(name = "seedingDuration", required = true)
    protected BigDecimal seedingDuration;
    @XmlAttribute(name = "showIconsOnPDA", required = true)
    protected boolean showIconsOnPDA;
    @XmlAttribute(name = "threshingDuration", required = true)
    protected BigDecimal threshingDuration;
    @XmlAttribute(name = "timeScale", required = true)
    protected BigDecimal timeScale;
    @XmlAttribute(name = "timeSinceLastRain", required = true)
    protected BigDecimal timeSinceLastRain;
    @XmlAttribute(name = "traveledDistance", required = true)
    protected BigDecimal traveledDistance;
    @XmlAttribute(name = "valid", required = true)
    protected boolean valid;

    /**
     * Gets the value of the farmSiloAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link FarmSiloAmounts }
     *     
     */
    public FarmSiloAmounts getFarmSiloAmounts() {
        return farmSiloAmounts;
    }

    /**
     * Sets the value of the farmSiloAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarmSiloAmounts }
     *     
     */
    public void setFarmSiloAmounts(FarmSiloAmounts value) {
        this.farmSiloAmounts = value;
    }

    /**
     * Gets the value of the fillTypePrices property.
     * 
     * @return
     *     possible object is
     *     {@link FillTypePrices }
     *     
     */
    public FillTypePrices getFillTypePrices() {
        return fillTypePrices;
    }

    /**
     * Sets the value of the fillTypePrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillTypePrices }
     *     
     */
    public void setFillTypePrices(FillTypePrices value) {
        this.fillTypePrices = value;
    }

    /**
     * Gets the value of the rains property.
     * 
     * @return
     *     possible object is
     *     {@link Rains }
     *     
     */
    public Rains getRains() {
        return rains;
    }

    /**
     * Sets the value of the rains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rains }
     *     
     */
    public void setRains(Rains value) {
        this.rains = value;
    }

    /**
     * Gets the value of the currentRain property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentRain }
     *     
     */
    public CurrentRain getCurrentRain() {
        return currentRain;
    }

    /**
     * Sets the value of the currentRain property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentRain }
     *     
     */
    public void setCurrentRain(CurrentRain value) {
        this.currentRain = value;
    }

    /**
     * Gets the value of the lastRain property.
     * 
     * @return
     *     possible object is
     *     {@link LastRain }
     *     
     */
    public LastRain getLastRain() {
        return lastRain;
    }

    /**
     * Sets the value of the lastRain property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastRain }
     *     
     */
    public void setLastRain(LastRain value) {
        this.lastRain = value;
    }

    /**
     * Gets the value of the autoBackupIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutoBackupIndex() {
        return autoBackupIndex;
    }

    /**
     * Sets the value of the autoBackupIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutoBackupIndex(BigInteger value) {
        this.autoBackupIndex = value;
    }

    /**
     * Gets the value of the completedMowingMissions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompletedMowingMissions() {
        return completedMowingMissions;
    }

    /**
     * Sets the value of the completedMowingMissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompletedMowingMissions(BigInteger value) {
        this.completedMowingMissions = value;
    }

    /**
     * Gets the value of the completedTransportMissions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompletedTransportMissions() {
        return completedTransportMissions;
    }

    /**
     * Sets the value of the completedTransportMissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompletedTransportMissions(BigInteger value) {
        this.completedTransportMissions = value;
    }

    /**
     * Gets the value of the currentDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrentDay() {
        return currentDay;
    }

    /**
     * Sets the value of the currentDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrentDay(BigInteger value) {
        this.currentDay = value;
    }

    /**
     * Gets the value of the dayTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDayTime() {
        return dayTime;
    }

    /**
     * Sets the value of the dayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDayTime(BigDecimal value) {
        this.dayTime = value;
    }

    /**
     * Gets the value of the densityMapRevision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDensityMapRevision() {
        return densityMapRevision;
    }

    /**
     * Sets the value of the densityMapRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDensityMapRevision(BigInteger value) {
        this.densityMapRevision = value;
    }

    /**
     * Gets the value of the difficulty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDifficulty() {
        return difficulty;
    }

    /**
     * Sets the value of the difficulty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDifficulty(BigInteger value) {
        this.difficulty = value;
    }

    /**
     * Gets the value of the eastState1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEastState1() {
        return eastState1;
    }

    /**
     * Sets the value of the eastState1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEastState1(BigInteger value) {
        this.eastState1 = value;
    }

    /**
     * Gets the value of the eastState2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEastState2() {
        return eastState2;
    }

    /**
     * Sets the value of the eastState2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEastState2(BigInteger value) {
        this.eastState2 = value;
    }

    /**
     * Gets the value of the expenses property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpenses() {
        return expenses;
    }

    /**
     * Sets the value of the expenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpenses(BigDecimal value) {
        this.expenses = value;
    }

    /**
     * Gets the value of the foundHelpIcons property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFoundHelpIcons() {
        return foundHelpIcons;
    }

    /**
     * Sets the value of the foundHelpIcons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFoundHelpIcons(BigInteger value) {
        this.foundHelpIcons = value;
    }

    /**
     * Gets the value of the foundHorseshoeCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFoundHorseshoeCount() {
        return foundHorseshoeCount;
    }

    /**
     * Sets the value of the foundHorseshoeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFoundHorseshoeCount(BigInteger value) {
        this.foundHorseshoeCount = value;
    }

    /**
     * Gets the value of the foundHorseshoes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoundHorseshoes() {
        return foundHorseshoes;
    }

    /**
     * Sets the value of the foundHorseshoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoundHorseshoes(String value) {
        this.foundHorseshoes = value;
    }

    /**
     * Gets the value of the fuelUsage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFuelUsage() {
        return fuelUsage;
    }

    /**
     * Sets the value of the fuelUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFuelUsage(BigDecimal value) {
        this.fuelUsage = value;
    }

    /**
     * Gets the value of the hectaresSeeded property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHectaresSeeded() {
        return hectaresSeeded;
    }

    /**
     * Sets the value of the hectaresSeeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHectaresSeeded(BigDecimal value) {
        this.hectaresSeeded = value;
    }

    /**
     * Gets the value of the hectaresThreshed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHectaresThreshed() {
        return hectaresThreshed;
    }

    /**
     * Sets the value of the hectaresThreshed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHectaresThreshed(BigDecimal value) {
        this.hectaresThreshed = value;
    }

    /**
     * Gets the value of the hectaresWorked property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHectaresWorked() {
        return hectaresWorked;
    }

    /**
     * Sets the value of the hectaresWorked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHectaresWorked(BigDecimal value) {
        this.hectaresWorked = value;
    }

    /**
     * Gets the value of the loan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoan() {
        return loan;
    }

    /**
     * Sets the value of the loan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoan(BigInteger value) {
        this.loan = value;
    }

    /**
     * Gets the value of the loanAnnualInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoanAnnualInterestRate() {
        return loanAnnualInterestRate;
    }

    /**
     * Sets the value of the loanAnnualInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoanAnnualInterestRate(BigInteger value) {
        this.loanAnnualInterestRate = value;
    }

    /**
     * Gets the value of the longSnowBreakCounter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLongSnowBreakCounter() {
        return longSnowBreakCounter;
    }

    /**
     * Sets the value of the longSnowBreakCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLongSnowBreakCounter(BigInteger value) {
        this.longSnowBreakCounter = value;
    }

    /**
     * Gets the value of the mapId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapId() {
        return mapId;
    }

    /**
     * Sets the value of the mapId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapId(String value) {
        this.mapId = value;
    }

    /**
     * Gets the value of the missionFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMissionFrequency() {
        return missionFrequency;
    }

    /**
     * Sets the value of the missionFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMissionFrequency(BigInteger value) {
        this.missionFrequency = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMoney(BigInteger value) {
        this.money = value;
    }

    /**
     * Gets the value of the plantGrowthRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlantGrowthRate() {
        return plantGrowthRate;
    }

    /**
     * Sets the value of the plantGrowthRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlantGrowthRate(BigInteger value) {
        this.plantGrowthRate = value;
    }

    /**
     * Gets the value of the playTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPlayTime() {
        return playTime;
    }

    /**
     * Sets the value of the playTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPlayTime(BigDecimal value) {
        this.playTime = value;
    }

    /**
     * Gets the value of the resetVehicles property.
     * 
     */
    public boolean isResetVehicles() {
        return resetVehicles;
    }

    /**
     * Sets the value of the resetVehicles property.
     * 
     */
    public void setResetVehicles(boolean value) {
        this.resetVehicles = value;
    }

    /**
     * Gets the value of the revenue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRevenue() {
        return revenue;
    }

    /**
     * Sets the value of the revenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRevenue(BigDecimal value) {
        this.revenue = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevision(BigInteger value) {
        this.revision = value;
    }

    /**
     * Gets the value of the saveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSaveDate() {
        return saveDate;
    }

    /**
     * Sets the value of the saveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSaveDate(XMLGregorianCalendar value) {
        this.saveDate = value;
    }

    /**
     * Gets the value of the seedUsage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSeedUsage() {
        return seedUsage;
    }

    /**
     * Sets the value of the seedUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSeedUsage(BigDecimal value) {
        this.seedUsage = value;
    }

    /**
     * Gets the value of the seedingDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSeedingDuration() {
        return seedingDuration;
    }

    /**
     * Sets the value of the seedingDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSeedingDuration(BigDecimal value) {
        this.seedingDuration = value;
    }

    /**
     * Gets the value of the showIconsOnPDA property.
     * 
     */
    public boolean isShowIconsOnPDA() {
        return showIconsOnPDA;
    }

    /**
     * Sets the value of the showIconsOnPDA property.
     * 
     */
    public void setShowIconsOnPDA(boolean value) {
        this.showIconsOnPDA = value;
    }

    /**
     * Gets the value of the threshingDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getThreshingDuration() {
        return threshingDuration;
    }

    /**
     * Sets the value of the threshingDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setThreshingDuration(BigDecimal value) {
        this.threshingDuration = value;
    }

    /**
     * Gets the value of the timeScale property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeScale() {
        return timeScale;
    }

    /**
     * Sets the value of the timeScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeScale(BigDecimal value) {
        this.timeScale = value;
    }

    /**
     * Gets the value of the timeSinceLastRain property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeSinceLastRain() {
        return timeSinceLastRain;
    }

    /**
     * Sets the value of the timeSinceLastRain property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeSinceLastRain(BigDecimal value) {
        this.timeSinceLastRain = value;
    }

    /**
     * Gets the value of the traveledDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTraveledDistance() {
        return traveledDistance;
    }

    /**
     * Sets the value of the traveledDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTraveledDistance(BigDecimal value) {
        this.traveledDistance = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

}
