//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 07:42:28 AM BST 
//


package fs2013;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fs2013 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fs2013
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CareerSavegame }
     * 
     */
    public CareerSavegame createCareerSavegame() {
        return new CareerSavegame();
    }

    /**
     * Create an instance of {@link FarmSiloAmounts }
     * 
     */
    public FarmSiloAmounts createFarmSiloAmounts() {
        return new FarmSiloAmounts();
    }

    /**
     * Create an instance of {@link FarmSiloAmount }
     * 
     */
    public FarmSiloAmount createFarmSiloAmount() {
        return new FarmSiloAmount();
    }

    /**
     * Create an instance of {@link FillTypePrices }
     * 
     */
    public FillTypePrices createFillTypePrices() {
        return new FillTypePrices();
    }

    /**
     * Create an instance of {@link FillTypePrice }
     * 
     */
    public FillTypePrice createFillTypePrice() {
        return new FillTypePrice();
    }

    /**
     * Create an instance of {@link Rains }
     * 
     */
    public Rains createRains() {
        return new Rains();
    }

    /**
     * Create an instance of {@link Rain }
     * 
     */
    public Rain createRain() {
        return new Rain();
    }

    /**
     * Create an instance of {@link CurrentRain }
     * 
     */
    public CurrentRain createCurrentRain() {
        return new CurrentRain();
    }

    /**
     * Create an instance of {@link LastRain }
     * 
     */
    public LastRain createLastRain() {
        return new LastRain();
    }

}
